### ISSUE TITLE
parseSize issue on Go/Mo/Ko

### ISSUE THREAD

**Issue by maxcore** [elneruda/couchpotato.provider.libertalia#2]
Merci pour le plug in !
mais il trouve rien ..  

fnt fonctionne parfaitement

**Comment by elneruda** [comment]
Essaye en décochant tous les providers excepté libertalia. Après libertalia n'est pas hyper fourni, et il dispose de peu de seeders, CP génère une note de priorité entre les différentes release de chaque provider en fonction du nombre de seed, de leech, ... Il est possible qu'un autre provider remporte le plus haut score à chaque fois.

**Comment by maxcore** [comment]
J'ai faite ce test avant et non rien je te metterais un debug log ce soir

**Comment by maxcore** [comment]
@elneruda  ok je vois que l'a y trouve la releases mais je crois qu'il y a un problème avec les tailles des releases , il ignore beaucoup de releases pour 0mb

```
11-24 21:40:24 INFO
[tato.core.plugins.release] Ignored, size "0MB" to low: No Escape 2015 MULTi 1080p BluRay x264-LOST
11-24 21:40:24 INFO
[tato.core.plugins.release] Ignored, size "0MB" to low: No Escape 2015 MULTi 1080p BluRay x264-LOST

```

![capture d ecran 2015-11-24 21 55 48](https://cloud.githubusercontent.com/assets/4043787/11387197/3c288cbc-92f6-11e5-8719-bb80688fbfa5.png)

**Comment by maxcore** [comment]
@djoole

tu sais comment avoir le size des releases je cherche et je trouve pas ..

**Comment by djoole** [comment]
En voyant ton screenshot qui indique des tailles n/a j'ai tendance à penser que l'info n'existe pas sur le tracker..

**Comment by maxcore** [comment]
@djoole 
pourtant si : 

```
<td class="number_column nobr">5.39 Go</td></tr>
```

![capture d ecran 2015-11-28 09 01 06](https://cloud.githubusercontent.com/assets/4043787/11452265/b8124776-95af-11e5-8228-cc25fea1a7f0.png)

**Comment by elneruda** [comment]
Je viens de comprendre : la méthode parseSize (https://github.com/RuudBurger/CouchPotatoServer/blob/master/couchpotato/core/media/_base/providers/base.py) peut évaluer une chaine qui contient "XXX GB/MB/KB" dans le cas fnt les tailles de fichiers sont bien définies comme cela par contre pour libertalia le format est le suivant : "XXX Go/Mo/Ko"
Je fais la correction.

**Comment by elneruda** [comment]
en fait la meilleure solution serait de remplacer dans CP ceci : 

size_gb = ['gb', 'gib']
size_mb = ['mb', 'mib']
size_kb = ['kb', 'kib']

par ceci : 

size_gb = ['gb', 'gib','go']
size_mb = ['mb', 'mib','mo']
size_kb = ['kb', 'kib','ko']

Avec ma vieille version de CP2 FR en local c'est le cas et ça fonctionnait..

**Comment by elneruda** [comment]
@maxcore  Je viens de corriger.

**Comment by maxcore** [comment]
Merciiiiiiiii

**Comment by elneruda** [comment]
Fixed on #bba217e3ed4a7f18bbcb2a5932d265797a898d1f
